export const EXPENSE_CATEGORIES = [
  "Renta",
  "Servicios (Luz, Agua, Internet, etc.)",
  "Sueldos y Nóminas",
  "Proveedores / Inventario",
  "Marketing y Publicidad",
  "Seguros",
  "Impuestos",
  "Mantenimiento",
  "Transporte y Logística",
  "Software y Suscripciones",
  "Capacitación",
  "Comisiones Bancarias",
  "Otros",
];
